-- ============================================================
-- Olympic Hotel — Auth, rollen/rechten (RBAC) & RLS  (basis)
-- Rollen: medewerker < manager < directie < admin
-- ============================================================

-- ---------- Enums ----------
create type public.app_role as enum ('medewerker', 'manager', 'directie', 'admin');
create type public.app_permission as enum (
  'users.read', 'users.manage', 'tools.manage',
  'bookings.create', 'bookings.read', 'bookings.update', 'bookings.delete'
);

-- ---------- Tabellen ----------
-- Profiel (1-op-1 met auth.users)
create table public.profiles (
  id          uuid primary key references auth.users on delete cascade,
  email       text,
  full_name   text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Rol(len) per gebruiker
create table public.user_roles (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users on delete cascade,
  role       public.app_role not null,
  created_at timestamptz not null default now(),
  unique (user_id, role)
);

-- Rechten per rol
create table public.role_permissions (
  id         bigint generated by default as identity primary key,
  role       public.app_role not null,
  permission public.app_permission not null,
  unique (role, permission)
);

-- ---------- Seed: rechten-matrix ----------
insert into public.role_permissions (role, permission) values
  -- admin: alles
  ('admin','users.read'), ('admin','users.manage'), ('admin','tools.manage'),
  ('admin','bookings.create'), ('admin','bookings.read'), ('admin','bookings.update'), ('admin','bookings.delete'),
  -- directie: alles behalve gebruikersbeheer
  ('directie','users.read'), ('directie','tools.manage'),
  ('directie','bookings.create'), ('directie','bookings.read'), ('directie','bookings.update'), ('directie','bookings.delete'),
  -- manager: boekingen volledig + gebruikers lezen
  ('manager','users.read'),
  ('manager','bookings.create'), ('manager','bookings.read'), ('manager','bookings.update'), ('manager','bookings.delete'),
  -- medewerker: dagelijkse boekingen (geen verwijderen)
  ('medewerker','bookings.create'), ('medewerker','bookings.read'), ('medewerker','bookings.update');

-- ---------- Autorisatie-helpers (security definer => omzeilen RLS, geen recursie) ----------
create or replace function public.authorize(requested_permission public.app_permission)
returns boolean
language plpgsql stable security definer set search_path = ''
as $$
declare bound int;
begin
  select count(*) into bound
  from public.role_permissions rp
  join public.user_roles ur on ur.role = rp.role
  where rp.permission = requested_permission
    and ur.user_id = (select auth.uid());
  return bound > 0;
end;
$$;

create or replace function public.has_role(check_role public.app_role)
returns boolean
language sql stable security definer set search_path = ''
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = (select auth.uid()) and role = check_role
  );
$$;

-- ---------- Trigger: nieuwe auth-gebruiker -> profiel ----------
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name')
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------- Trigger: updated_at ----------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- ============================================================
-- Row Level Security
-- ============================================================
alter table public.profiles         enable row level security;
alter table public.user_roles       enable row level security;
alter table public.role_permissions enable row level security;

-- profiles
create policy "Eigen profiel lezen"
  on public.profiles for select to authenticated
  using ( (select auth.uid()) = id );

create policy "Beheer leest alle profielen"
  on public.profiles for select to authenticated
  using ( public.authorize('users.read') );

create policy "Eigen profiel bijwerken"
  on public.profiles for update to authenticated
  using ( (select auth.uid()) = id )
  with check ( (select auth.uid()) = id );

create policy "Admin beheert profielen"
  on public.profiles for all to authenticated
  using ( public.authorize('users.manage') )
  with check ( public.authorize('users.manage') );

-- user_roles
create policy "Eigen rollen lezen"
  on public.user_roles for select to authenticated
  using ( (select auth.uid()) = user_id );

create policy "Beheer leest alle rollen"
  on public.user_roles for select to authenticated
  using ( public.authorize('users.read') );

create policy "Admin beheert rollen"
  on public.user_roles for all to authenticated
  using ( public.authorize('users.manage') )
  with check ( public.authorize('users.manage') );

-- role_permissions (matrix mag iedereen ingelogd lezen; alleen admin wijzigen)
create policy "Ingelogd leest rechten-matrix"
  on public.role_permissions for select to authenticated
  using ( true );

create policy "Admin beheert rechten-matrix"
  on public.role_permissions for all to authenticated
  using ( public.authorize('users.manage') )
  with check ( public.authorize('users.manage') );
